name: Latest posts workflow
on:
  schedule:
    - cron: '30 12,22 * * *' # Runs at 12:30 and 22:30 UTC every day.
  workflow_dispatch:
  push: { branches: [ "master", "main" ] }
jobs:
  update-readme:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      # Doc https://github.com/lowlighter/metrics#-documentation
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: bric3
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Europe/Paris

          plugin_discussions: yes
          plugin_discussions_categories: yes

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: markup, programming
          plugin_languages_limit: 4
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          plugin_notable: yes
          plugin_notable_filter: stars:>1000 sort:stargazers
          plugin_notable_from: all
#          plugin_notable_from: organization
          plugin_notable_repositories: yes
#          plugin_notable_types: commit
          plugin_notable_self: true

          repositories_forks: yes
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://blog.arkey.fr/posts/index.xml"
          max_post_count: 10
          template: "- $date : [**$title**]($url)  $newline    <blockquote>$description</blockquote>  $newline$newline"
          date_format: yyyy-mm-dd
          tag_post_pre_newline: true
          item_exec: |
            post.description = post.description.replace(/(?:\r\n|\r|\n)/, '').replace(/(?:\r\n|\r|\n)+$/, '')
                                               .replace(/(?:\r\n|\r|\n)/g, '<br>')
                                               .replace(/<\/?(div|p)[^>]*>/g, '')
                                               .trim();

                    
